#!/bin/bash

# OpenWebUI Plugin 一键复制脚本
# 让用户更容易安装

cd /Users/ywc/ai-stack-super-enhanced/openwebui-plugin

echo "═══════════════════════════════════════════════════════════"
echo "   🚀 OpenWebUI Plugin 一键准备安装"
echo "═══════════════════════════════════════════════════════════"
echo ""

# 复制Plugin到剪贴板
cat ai_stack_intelligent_plugin.py | pbcopy

echo "✅ AI Stack Intelligent Plugin 已复制到剪贴板"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 现在在OpenWebUI浏览器窗口中操作："
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  找到左下角的用户头像（圆形图标）"
echo "   └─ 如果看不到，可能需要先登录"
echo ""
echo "2️⃣  点击头像，选择 'Settings'"
echo ""
echo "3️⃣  在左侧菜单找到 'Functions'"
echo "   └─ 可能在 'Workspace' 下"
echo ""
echo "4️⃣  点击右上角的 '+' 按钮"
echo ""
echo "5️⃣  在代码编辑器中："
echo "   └─ 按 Command+V 粘贴"
echo "   └─ 点击 'Save'"
echo ""
echo "6️⃣  点击Plugin的 ⚙️ 图标"
echo ""
echo "7️⃣  配置以下内容（重要！）："
echo ""
echo "   API地址:"
echo "     rag_api: http://host.docker.internal:8011"
echo "     erp_api: http://host.docker.internal:8013"
echo "     stock_api: http://host.docker.internal:8014"
echo "     learning_api: http://host.docker.internal:8019"
echo ""
echo "   功能开关（全部打开）:"
echo "     ✅ enable_auto_rag: true"
echo "     ✅ enable_smart_routing: true"
echo "     ✅ enable_interaction_learning: true"
echo "     ✅ enable_expert_analysis: true"
echo "     ✅ enable_auto_rag_ingest: true"
echo "     ✅ enable_self_evolution: true"
echo ""
echo "8️⃣  保存配置"
echo ""
echo "9️⃣  确保Plugin左侧的开关是绿色（已启用）"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 安装完成后测试"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "在OpenWebUI聊天框输入："
echo ""
echo "  什么是深度学习？"
echo ""
echo "应该看到："
echo "  🧠 AI Stack智能分析中..."
echo "  ✅ 已集成RAG知识+实时数据+专家分析"
echo "  [AI专业回答，包含RAG知识和专家建议]"
echo ""
echo "如果看到这些，说明安装成功！ 🎉"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ 如果看不到Functions菜单"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "原因1: 未登录"
echo "  → 先注册/登录OpenWebUI"
echo ""
echo "原因2: 不是管理员"
echo "  → 使用首个注册的账号"
echo ""
echo "原因3: 直接访问Functions URL"
echo "  → http://localhost:3000/workspace/functions"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "💡 如果OpenWebUI安装困难，建议使用："
echo "   统一控制台: http://localhost:8000"
echo "   (已经可以访问所有AI Stack功能)"
echo ""
echo "═══════════════════════════════════════════════════════════"



