# 文件处理器配置 - 对应需求 1.1 (所有格式文件处理)
# 文件编号: 17
# 路径: ⚙️ Configuration Center/modules/rag/file-processors.yaml

file_processors:
  # 通用文件解析配置
  universal_parser:
    enabled: true
    max_file_size_mb: 1000
    supported_extensions:
      # 办公文件
      - ".doc"
      - ".docx"
      - ".ppt"
      - ".pptx"
      - ".xls"
      - ".xlsx"
      - ".pdf"
      - ".rtf"
      - ".odt"
      - ".ods"
      - ".odp"

      # 电子书文件
      - ".epub"
      - ".mobi"
      - ".azw3"
      - ".fb2"
      - ".ibooks"

      # 编程文件
      - ".py"
      - ".java"
      - ".cpp"
      - ".c"
      - ".js"
      - ".ts"
      - ".html"
      - ".css"
      - ".sql"
      - ".json"
      - ".xml"
      - ".yaml"
      - ".yml"

      # 图片文件
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
      - ".bmp"
      - ".tiff"
      - ".svg"
      - ".webp"

      # 语音文件
      - ".mp3"
      - ".wav"
      - ".flac"
      - ".aac"
      - ".m4a"
      - ".ogg"

      # 视频文件
      - ".mp4"
      - ".avi"
      - ".mov"
      - ".wmv"
      - ".flv"
      - ".mkv"
      - ".webm"

      # 思维导图文件
      - ".xmind"
      - ".mm"
      - ".mmap"
      - ".freemind"

      # 数据文件
      - ".csv"
      - ".tsv"
      - ".db"
      - ".sqlite"
      - ".parquet"
      - ".feather"

      # 文本文件
      - ".txt"
      - ".md"
      - ".rst"
      - ".log"

  # 办公文档处理器配置
  office_documents:
    enabled: true
    extract_images: true
    preserve_formatting: true
    table_processing: true
    header_footer_removal: true

  # 电子书提取器配置
  ebooks:
    enabled: true
    extract_metadata: true
    chapter_detection: true
    toc_processing: true
    image_extraction: true

  # 代码分析器配置
  code_analyzer:
    enabled: true
    syntax_highlighting: true
    function_extraction: true
    comment_processing: true
    dependency_analysis: true
    language_specific_rules: true

  # 图片OCR处理器配置
  image_ocr:
    enabled: true
    languages:
      - "chinese"
      - "english"
      - "japanese"
      - "korean"
    confidence_threshold: 0.8
    preprocess_images: true
    deskew_enabled: true

  # 音频转录器配置
  audio_transcriber:
    enabled: true
    model: "whisper-large"
    languages:
      - "zh"
      - "en"
      - "ja"
      - "ko"
    diarization: true
    speaker_count: 5
    timestamp_generation: true

  # 视频帧提取器配置
  video_processor:
    enabled: true
    frame_extraction_interval: 2  # seconds
    keyframe_detection: true
    audio_extraction: true
    subtitle_processing: true

  # 思维导图解析器配置
  mindmap_parser:
    enabled: true
    extract_hierarchy: true
    node_relationships: true
    central_topic_detection: true

  # 数据库文件处理器配置
  database_files:
    enabled: true
    table_schema_extraction: true
    sample_data_processing: true
    relationship_detection: true

  # 文本处理器配置
  text_processors:
    intelligent_chunking:
      enabled: true
      semantic_boundary_detection: true
      context_preservation: true

    semantic_cleaning:
      enabled: true
      remove_duplicates: true
      normalize_encoding: true
      fix_typos: true

    entity_relationship_extraction:
      enabled: true
      entity_types:
        - "person"
        - "organization"
        - "location"
        - "date"
        - "product"
      relationship_detection: true

    quality_validation:
      enabled: true
      min_content_length: 10
      max_content_length: 10000
      language_detection: true
      spam_detection: true

  # 媒体处理器配置
  media_processors:
    video_content_analysis:
      enabled: true
      scene_detection: true
      object_recognition: true
      text_overlay_processing: true

    audio_content_extraction:
      enabled: true
      emotion_detection: true
      topic_segmentation: true

    image_semantic_analysis:
      enabled: true
      object_detection: true
      scene_classification: true
      text_detection: true

  # 性能配置
  performance:
    parallel_processing: true
    max_workers: 8
    batch_processing: true
    batch_size: 50
    memory_optimization: true

  # 错误处理配置
  error_handling:
    continue_on_error: true
    max_retries: 3
    retry_delay_seconds: 5
    fallback_processors: true