# 知识图谱配置 - 对应需求 1.8, 1.9
# 文件编号: 19
# 路径: ⚙️ Configuration Center/modules/rag/knowledge-graph.yaml

knowledge_graph:
  # 核心配置
  core:
    enabled: true
    version: "1.0.0"
    database: "nebula"  # nebula, neo4j, janusgraph
    auto_build: true

  # 图数据库配置
  graph_database:
    connection:
      host: "localhost"
      port: 9669
      username: "ai_stack"
      password: "${KG_PASSWORD}"
      space: "ai_stack_kg"
      timeout_seconds: 30

    storage:
      persistence_enabled: true
      storage_path: "/Volumes/Huawei-1/ai-stack-data/knowledge_graph"
      backup_enabled: true
      backup_interval_hours: 12

  # 图谱构建配置
  graph_construction:
    enabled: true
    source: "rag"  # rag, erp, stock, content, trend

    entity_extraction:
      enabled: true
      entity_types:
        - "person"
        - "organization"
        - "location"
        - "product"
        - "concept"
        - "event"
        - "technology"
        - "industry"
      confidence_threshold: 0.8

    relationship_extraction:
      enabled: true
      relationship_types:
        - "is_part_of"
        - "is_type_of"
        - "located_in"
        - "works_for"
        - "created_by"
        - "related_to"
        - "influences"
      min_confidence: 0.7

    attribute_extraction:
      enabled: true
      extract_temporal: true
      extract_quantitative: true
      extract_descriptive: true

  # 动态更新配置
  dynamic_updating:
    enabled: true
    update_strategy: "incremental"  # incremental, full, smart
    update_interval_minutes: 60
    change_detection: true
    versioning_enabled: true

  # 查询优化配置
  query_optimization:
    enabled: true
    cache_enabled: true
    cache_ttl_minutes: 30
    query_timeout_seconds: 10
    max_path_length: 10

    indexing:
      entity_index: true
      relationship_index: true
      fulltext_index: true

  # 知识推理配置
  knowledge_inference:
    enabled: true
    inference_rules:
      - "transitive_closure"
      - "symmetry"
      - "inverse_relationships"
    reasoning_depth: 3
    confidence_propagation: true

  # RAG 集成配置 - 对应需求 1.8
  rag_integration:
    enabled: true
    bidirectional_sync: true
    sync_interval_minutes: 30
    entity_linking: true
    context_enrichment: true

  # 多模块集成配置
  module_integrations:
    erp_integration:
      enabled: true
      business_entities: true
      process_flows: true
      kpi_relationships: true

    stock_integration:
      enabled: true
      company_entities: true
      market_relationships: true
      investment_strategies: true

    content_integration:
      enabled: true
      topic_entities: true
      content_relationships: true
      trend_analysis: true

    trend_integration:
      enabled: true
      trend_entities: true
      causal_relationships: true
      impact_analysis: true

  # 可视化配置 - 对应需求 1.9
  visualization:
    enabled: true
    web_interface: true
    real_time_updates: true
    interactive_exploration: true

    layout_algorithms:
      - "force_directed"
      - "hierarchical"
      - "circular"

    filtering:
      entity_type_filter: true
      relationship_filter: true
      confidence_filter: true
      temporal_filter: true

  # 性能配置
  performance:
    batch_processing: true
    batch_size: 1000
    parallel_processing: true
    max_workers: 8
    memory_optimization: true

  # 监控配置
  monitoring:
    health_check_enabled: true
    graph_metrics_enabled: true
    query_performance_tracking: true
    storage_monitoring: true

  # 进化学习配置
  evolution:
    self_learning_enabled: true
    pattern_recognition: true
    relationship_discovery: true
    schema_evolution: true
    learning_rate: 0.1