   /enhanced_rag_kg
   ├── /api
   │   ├── app.py
   │   ├── routes.py
   │   ├── models.py
   │   └── utils.py
   ├── /pipelines
   │   ├── hybrid_search.py
   │   └── smart_ingestion_pipeline.py
   ├── /preprocessors
   │   └── kg_simple.py
   ├── /core
   │   └── semantic_grouping.py
   ├── /data
   │   ├── index.json
   │   └── kg_snapshot.json
   ├── /tests
   │   ├── test_api.py
   │   └── test_pipeline.py
   ├── requirements.txt
   └── README.md